# fly.toml app configuration file generated for li-mastermind on 2023-11-21T19:43:09-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "li-mastermind"
primary_region = "sjc"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
